language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/Gemfile.rails-5_0
  - gemfiles/Gemfile.rails-4_2
  - gemfiles/Gemfile.rails-3_2

matrix:
  include:
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-edge
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5_0
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5_0
    - rvm: 2.1.9
      gemfile: gemfiles/Gemfile.rails-5_0
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-edge
